// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    zombies_contract
    (
        init => init
        upgrade => upgrade
        generate_random_dna => generate_random_dna
        create_random_zombie => create_random_zombie
        feed_and_multiply => feed_and_multiply
        zombies => zombies
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
